### ISSUE TITLE
Implement ECS-Compatibility Mode

### ISSUE THREAD

**Issue by yaauie** [logstash-plugins/logstash-input-http_poller#117]
_This is a stub issue, and needs to be fleshed out with details specific to
this plugin._

***

As a part of the effort to make plugins able to run in an ECS-Compatible manner
by default in an upcoming release of Logstash, this plugin needs to either
implement an ECS-Compatibility mode or certify that it does not implicitly use
fields that conflict with ECS.

**Comment by kaisecheng** [comment]
| Legacy  | ECS |
| ------------- | ------------- |
| [http_poller_metadata][url] | [url][full] |
| [http_poller_metadata][method] | [http][request][method] |
| [http_poller_metadata][response_code] | [http][response][status][code] |
| [http_poller_metadata][response_message] | [http][response][body][content] |
| [http_poller_metadata][host] | [host][ip]  |
| [http_poller_metadata][response_headers] | [@metadata][input][http_poller][response][headers] |
| [http_poller_metadata][runtime_s]  | [@metadata][input][http_poller][response][time][second] |
| [http_poller_metadata][times_retried] | [@metadata][input][http_poller][request][retried] |
| [http_poller_metadata][name] | [@metadata][input][http_poller][request][name] |

**Comment by roaksoax** [comment]
Closing this issue as this has now been fixed in: https://github.com/logstash-plugins/logstash-input-http_poller/pull/129
