### ISSUE TITLE
Making the input plugin a filter plugin also

### ISSUE THREAD

**Issue by elvarb** [logstash-plugins/logstash-input-http_poller#12]
It would be extremely powerful to have a filter plugin on the same code base as the input filter.

This way we could use conditionals to do additional enrichment's in some cases.
- Input monitors elasticsearch health api
- If health is yellow do a filter check against the cluster api to see why it is yellow

With additional methods we could also automate reactions to events. Using post, delete and so on.

**Comment by andrewvc** [comment]
I'm interested in this, can you post a sample config for the filter API as you envision it?

**Comment by andrewvc** [comment]
Also @elvarb I've broken out the HTTP client into a [separate mixin plugin](https://github.com/logstash-plugins/logstash-mixin-http_client). For the use case you've mentioned, I feel like it'd be best to write a new plugin to do just that. That seems like a bit more logic than I'd like to put into a LogStash pipeline. 

With the plugin mixin it's very easy to write something like what you describe.

**Comment by elvarb** [comment]
Here is a rough example
```
input {
	http_poller {
		url => "http://internalapp.es/_cluster/health"
		interval => 60
		codec => "json"
		tags => ["elasticsearch"]
	}
}

filter {
	if "elasticsearch" in [tags] {
		if [status] != "green" {
			http_poller {
				url => "http://internalapp.es/_cluster/pending_tasks"
				codec => "json"
			}
			http_poller {
				url => "http://internalapp.es/_nodes/hot_threads"
				codec => "json"
			}
			http_poller {
				url => "http://internalapp.es/_cluster/stats"
				codec => "json"
			}
		}
	}
}

output {
	if "elasticsearch" in [tags] {
		elasticsearch {
			protocol => "http"
			host => "logs.es"
		}

		email {
			from => "elk@host.com"
			to => "error@host.com"
			subject => "%{[cluster_name]} is %{[status]}"
			via => "smtp"
			options => {
				smtpIporHost => "smtp.visa.is"
				port => 25
			}
			htmlbody => "Fielddata is %{[indices][fielddata][memory_size]} .... 
	}
}
```

This filter could also replace the elasticsearch filter since that just does a http api query and having one http filter that can be used in multiple of use cases.

This use case also highlights the need for a target option. So that if you do multiple queries to different elasticsearch health api's you very likely get repeated fieldnames.

This filter does exactly this also, https://github.com/elastic/logstash/issues/3489 but does it differently 

Logstash could then be used as an alerting platform that can provide context to the alerts. Touching the area where Bosun excels today.

**Comment by andrewvc** [comment]
@jordansissel @suyograo @colinsurprenant I'm curious if any of you have thoughts on this idea?

My thinking is that this may be biting off more logic than we'd want in a logstash plugin, and perhaps for this instance a custom plugin depending on the [HTTP client mixin](https://github.com/logstash-plugins/logstash-mixin-http_client) might be more appropriate, but I need to chew this over.

**Comment by elvarb** [comment]
Another example

**Input**
1. Query RabbitMQ queue statistc API

**Filter**
1. If queue is over 10.000 then query the Elasticsearch API to see the cluster and node state.

**Output**
1. Send RabbitMQ metrics to Graphite/InfluxDB
2. If queue is over 10.000 and Elasticsearch is green run exec to restart the Logstash indexing process. Send email that queue was above 10.000 and that the Logstash process was restarted
3. If queue is over 10.000 and Elasticsearch is yellow or red, send email with context.

And to work with this concept even further, query Graphite API / Grafana API and get a png graph picture to send in the email.

**Comment by andrewvc** [comment]
That's a good example! I'm becoming more and more persuaded. The only trouble is I'm not sure if something that complex should be in a config file or in a specialized plugin. Complex configs like that can be hard to test.

@maximede do you have any thoughts here?

**Comment by maximede** [comment]
Well, I think that the use case is pertinent and that it would be really great to be able to do that kind of stuff.
@andrewvc I think that if we make a http_poller filter, the logstash config file won't be that complicated. My only concern is that the event could contain a lot of fields, with possibly some duplicates. In that case, maybe #13 could become useful. 
I don't really see what you mean by "config file vs specialized plugin". Do you mean something else than the http_poller filter ? Could you provide an example ? 
I personally don't think that @elvarb config example is that complicated.

**Comment by andrewvc** [comment]
@maximede I just was wondering if @elvarb 's example might be best implemented fully as its own ruby plugin. But after speaking with @jsvd I think the filter makes sense, I've been convinced :). 

I'm going to focus on releasing the input for now, but I'll create a new filter plugin based on the input. It'll have to be careful with background threads to avoid stalling the pipeline.

**Comment by jsvd** [comment]
My only concern on filters that call out of the jvm is the fact that filters are evaluated in sequence.
This means that you need to be very aware that introducing a http pooler filter can bog down the pipeline considerably. A pipeline like:

```
input {
  generator { count => 30 message => "1"}
}
filter {
  ruby { code => "sleep 1" }
  ruby { code => "sleep 1000" }
  ruby { code => "sleep 1" }
}
output { stdout { }}
```

Will always take 1+1000+1 seconds per event. There's nothing "async" we can do here, as we need the event to go through the filter so it can be handled by the next.

To put in another way, if each http_pooler filter request takes 1ms, the pipeline won't be faster than 1000 events per second (with `filter_workers`==1)

as long as that expectation is managed, this interesting to have, as enrichment is a very much requested feature.

**Comment by andrewvc** [comment]
@jsvd I'm thinking I can implement this filter as fully async using the thread mechanisms present in Manticore. What are your thoughts there? Check out the 'background' functionality in the [Manticore readme](https://github.com/cheald/manticore).

**Comment by elvarb** [comment]
I agree with @maximede that the number of fields could become an issue, expecialy if query the node health api. In this use case that is not such a big problem since the output would only be very specific fields. 

The issue that can come up with so many fields is how Logstash splits Inputs, Filters and Outputs. For example I have a condition in my config that if a certain event comes up then a new field is generated in a human readable format. This field is then sent to a chat room but since it is a part of the object passed on to the output process it also gets sent to Elasticsearch where it might not be needed. The elasticsearch output can only whitelist fields with the field option but not blacklist.

So for example, lets say we use the http poller input to query Elasticsearch health status, if something is found wrong do a http poller filter to query some other Elasticsearch api's. The object passed to the output is now huge and there is no good way to choose what gets sent to Elasticsearch and possibly other outputs as well.

**Comment by elvarb** [comment]
@jsvd This is kind of like if you have lots of incoming logs with IP addresses and want to do a dns filter on them, except this would be much much slower. So this can be a problem if you use it wrong.

I tend to have multiple Logstash processes running each for a very specific use case and each process has access to a few config files to ease management of them. My use case for a http filter would be to go with a http input.

When I think about it more you could have a waterfall like design. First a logstash process that does http input by querying api's. If something is found wrong the message is sent to a second logstash process that would do extra http filter checks. So here we have something like riemann where you can split messages to do different actions.

**Comment by andrewvc** [comment]
@elvarb the more I think about this, the more I think this should be a new plugin, maybe called `logstash-filter-http_request`. It would be based on the common core of [logstash-mixin-http_client](https://github.com/logstash-plugins/logstash-mixin-http_client), which is what the poller is based off of.

@elvarb do you have any interest in attempting an implementation of this?

**Comment by jsvd** [comment]
@elvarb yep I've done a similar thing with 2-4 steps of logstash processing, all using rabbitmq as a common.. "bus", it's a very valid architecture for working around some limitations of logstash scaling

**Comment by elvarb** [comment]
@andrewvc I agree it definitely should be a new plugin, the reason I created this issue here is because the difference between a input and a filter should probably be minimal. In my case I will be using the input http poller plugin soon but a filter plugin would be something that is nice to have but something I would not use very often.

What I mostly like about a filter like this is that it would open up so many more use cases for Logstash, not just logging but also monitoring. Lets say you have a website that uses lots of different API's on the backend, both internal and external. You could then have a http poller to query the webpage every minute but if something in the reply triggers a filter you could start a different query to the API services and finally send you an alert that your webpage is down because this specific api service is down.

You could also do this differently by for example use http poller to query all endpoints every minute and alert on those. 

Or you could send all the responses to Elasticsearch and use watcher to create the context.

Or you could send all the responses to Elasticsearch and have a different http poller query Elasticsearch.

So the more I think about it maybe we don't need a filter even though it might be nice but instead we need a good document listing various use cases and configs. Having a filter would mostly just make it simpler and require only Logstash.

@jsvd Sometimes it is the only way, you can have one queue and have two or more Logstash processes with the same config read from it but the major issues with that I have found is that the metric filter becomes nearly useless.

**Comment by jsvd** [comment]
@elvarb yep, what I did sometimes to ensure predictable "splitting" was take some data from the event, hash it, and use it as routing key % number of subscribers, this way 2 queue consumers would always get the same kind of data.

**Comment by elvarb** [comment]
I kinda cheated in my last usecase and just used the ruby filter to query a local ngnix instance.

The nginx instance was configured to be a reverse proxy for the actual api with very heavy caching so that only the first unique query hit the api and the rest hit the proxy.

```
	ruby {
		code => 'require "net/http"
			mid = event["mid"]
			urlstr = "http://localhost/json/#{mid}"
			url = URI.parse(urlstr)
			req = Net::HTTP::Get.new(url.to_s)
			res = Net::HTTP.start(url.host, url.port) {|http|http.request(req)}
			event["midlookup"] = res.body'
	}
```

**Comment by acchen97** [comment]
Closing with the [JDBC Streaming filter](https://www.elastic.co/guide/en/logstash/current/plugins-filters-jdbc_streaming.html) now released.
