### ISSUE TITLE
Wrong configuration to avoid certificate validation

### ISSUE THREAD

**Issue by gmoskovicz** [logstash-plugins/logstash-input-http_poller#48]
Looks like we are using `manticore` version `0.5.x`.

According to https://github.com/cheald/manticore/blob/v0.5.2/lib/manticore/client.rb#L148 ` ssl[:verify]` option should be used to remove verification. Currently in the documentation we mention that there is `ssl_certificate_validation` configuration, which looks like it has bee removed.

**Comment by gmoskovicz** [comment]
@andrewvc can you please confirm if `ssl_certificate_validation` still works?

**Comment by elvarb** [comment]
I'm running into an issue with using a self signed cert, but I'm not sure if that is the problem or not because simply nothing is coming through from hosts with self signed certs, nothing to debug. Does ssl_certificate_validation => false work?

**Comment by andrewvc** [comment]
This will be fixed in https://github.com/logstash-plugins/logstash-mixin-http_client/pull/20
