### ISSUE TITLE
Should this plugin record non 2xx responses as events?

### ISSUE THREAD

**Issue by andrewvc** [logstash-plugins/logstash-input-http_poller#9]
I'm thinking we should just log responses out of the 2xx range as errors rather than sending them through. There are a large number of reasons a request could fail (no DNS entry) for instance, that would not generate an error code at all. It is my vote that we just dump all those into `@logger.warn`.

**Comment by andrewvc** [comment]
Alternatively we could add a flag 'allow_failed_responses' that allows users to send a 404 or some such other response through the pipeline.

**Comment by djschny** [comment]
@andrewvc I vote for a the ability to enable to send them through as docs, and tagging with appropriate fields/codes. This would helps support the monitoring case. For example if I'm monitoring a website URL, I can now run reports of when it was unreachable, versus timed out, versus 500, etc.

**Comment by andrewvc** [comment]
@djschny that makes sense. In that case I'll make sure that all errors get passed through as events.

**Comment by suyograo** [comment]
@andrewvc with 2.0, we can start keeping metrics/counters on errors and expose them via API. For now I agree we should tag them and have them flow through

**Comment by andrewvc** [comment]
With #10 merged in all errors will now be tagged, and metadata about the failure will be sent as a doc.. Thanks for the suggestion @djschny
