### ISSUE TITLE
Does input-http_poller has OAUTH 2.0 support?

### ISSUE THREAD

**Issue by rkhapre** [logstash-plugins/logstash-input-http_poller#91]
I have a API which works on OAuth 2.0
A OAuth 2.0 API requires Authorization as header which holds bearer token
This is generated using Refresh Token, ClientID, Client Secret given values.( this are fixed values)

Currently this Authorization Header expired every 5 minutes, i have to go and generate it manually.I generate this through curl command . So i am not able to keep pipeline alive for a longer period of time.

In order to run my pipeline forever, i need to have this Authorization header token alive all the time.

Note : The API does provide Ruby as one of my client library. With this ruby script also the we can generate Authorization Bearer token

Has anyone tries OAuth 2.0 with http_poller?. This is common for all OAuth 2.0 APIs

Please let me know how i can achieve the solution

Regards
Ritesh

**Comment by yaauie** [comment]
Oy -- a 5-minute TTL on a `Bearer` token has got to be super painful to work with :weary:

No, this plugin does not provide the facility for dynamically altering the request (and to add it would be non-trivial); the same request is fired off each time that the scheduler triggers the poll.

In the past, I've personally used tools like [Kong](https://getkong.org/about/) as an API-gateway to modify requests dynamically; by adding a middleware that was capable of generating a current Bearer token (via a few lines of LUA), and authenticating my caller to that middleware via a less-fragile means, I was able to remove the fragility of a short-lived token from my caller.

The same can be achieved directly with nginx and a plugin like the [lua-nginx-module](https://github.com/openresty/lua-nginx-module), without all of the overhead of a managed configuration (Kong needs a database, provides a management console, etc.).

**Comment by rkhapre** [comment]
okay. This will be very laborious then. 
currently i am going with following automation

1. use client library like PHP to generate the token
2. As soon as #1 is done, generate the conf file dynamically
3. then run the pipeline, once done discard the conf files
4. Repeat step 1 to 3 in loop

This way i will get new token every time with conf file and pipeline will run.

Thanks for giving your ideas and i am closing this

**Comment by seanziee** [comment]
@rkhapre Hi I'm working on the same thing. I want to pull in GA data with the http_poller but I also have an OAuth2.0 to get through. Any advice or anything you can tell me to make this implementation easier? Thanks for your post because it's nice to know someone ran into the same thing as me!
